#!/bin/bash

# Change to OpenHAB's REST URL
HOST=127.0.0.1:8080

# Parameters
CMD=$1
ITEM=$2

# example usage
# oh_cmd get Door_Status
# oh_cmd set Light_Kitchen ON
# oh_cmd set Roller_Living 75
# oh_cmd get Roller_Living
# I think you got it ;)

case $CMD in
get)
    curl http://$HOST/rest/items/$ITEM/state
    ;;

set)
    VAL=$3
    echo -n $VAL | curl -X PUT --raw -T - http://$HOST/rest/items/$ITEM/state
    ;;
esac

