#!/bin/sh

### BEGIN INIT INFO
# Provides:          openhab
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Stop:       
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stopp OpenHAB
# Description:       
### END INIT INFO

# this is an Init-Script. Place it inside /etc/init.d, make it executable
# and place your openhab inside /home/pi/openhab. This script will copy
# this instance into RAM and will run it there

set -e

start ()
{
# start eibD
/usr/local/bin/eibd -d -TS usb:

# Create tmpfs in RAM for /openhab
mount -t tmpfs -o size=130M,uid=1000,gid=1000 none /openhab

# Sync persistant openHAB-Dir to fs in RAM
rsync -alr /home/pi/openhab/ /openhab/

# Start openHAB in screen-session
su -c "cd /openhab; screen -d -m sh start.sh 2>&1" pi &

sleep 5
mount -f -o remount,ro /
}

stop ()
{
mount -o remount,rw /
PID=$(ps -ef | grep java | grep -v grep | awk '{print $2}')
kill -9 $PID
sleep 2
}

save ()
{
rsync -avlr --delete --exclude .tmp --exclude .eclipse --exclude server /openhab/ /home/pi/openhab/
}

case "${1:-}" in
  save)
	echo "Persisting openHAB"
	save;;

  stop)
        echo "Stopping openHAB: "
	stop
	save
	umount -f /openhab;;

  start)
        echo "Starting openHAB: "
        start;;

  *)
        echo "Usage: ${0:-} {start|stop|save}" >&2
        exit 1
        ;;
esac
